/* logicoMod3: */

CREATE TABLE REMEDIOS (
    RMD_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    RMD_NOME VARCHAR(100) NOT NULL,
    RMD_VIA_DOSAGEM INTEGER,
    FK_FORMAS_FARMACEUTICAS_FRM_ID INTEGER,
    RMD_INDICACAO TEXT,
    RMD_CONTRAINDICACAO TEXT,
    RMD_DOSAGEM INTEGER(4) NOT NULL
);

CREATE TABLE FINALIDADE_REMEDIOS (
    FIN_DESCRICAO VARCHAR(100) NOT NULL UNIQUE,
    FIN_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE ESPECIALIDADES_MEDICAS (
    ESM_DESCRICAO VARCHAR(200) NOT NULL UNIQUE,
    ESM_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE PACIENTES (
    PAC_NOME VARCHAR(100) NOT NULL,
    PAC_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PAC_STATUS BOOLEAN NOT NULL,
    FK_PLANOS_PLN_ID INTEGER
);

CREATE TABLE MEDICOS (
    MED_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    MED_NOME VARCHAR(100) NOT NULL
);

CREATE TABLE EXAMES (
    EXM_NOME VARCHAR(100) NOT NULL,
    EXM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EXM_ANEXO_GUIA BLOB NOT NULL,
    EXM_OBS_SECRETARIO VARCHAR(200),
    EXM_AGENDAMENTO DATETIME,
    EXM_AUTORIZADO BOOLEAN,
    EXM_ANEXO_RESULTADO BLOB,
    EXM_OBS_PACIENTE VARCHAR(200),
    FK_MEDICOS_MED_ID INTEGER,
    FK_PACIENTES_PAC_ID INTEGER,
    UNIQUE (EXM_ANEXO_RESULTADO, EXM_ANEXO_GUIA)
);

CREATE TABLE PLANOS (
    PLN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PLN_INSTITUICAO VARCHAR(100) NOT NULL,
    PLN_NOME VARCHAR(100) NOT NULL UNIQUE,
    PLN_PRECO DOUBLE(8,2) NOT NULL
);

CREATE TABLE BENEFICIOS (
    BNF_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    BNF_DESCRICAO VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PAGAMENTOS (
    PAG_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PAG_VALOR_TOTAL DOUBLE(8,2) NOT NULL,
    PAG_DATA_PAGAMENTO DATE,
    PAG_VENCIMENTO DATE NOT NULL,
    FK_PACIENTES_PAC_ID INTEGER
);

CREATE TABLE PRESCRICOES (
    PRE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_MEDICOS_MED_ID INTEGER,
    FK_PACIENTES_PAC_ID INTEGER
);

CREATE TABLE PAGAMENTOS_MEDICOS (
    PGM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PGM_DATA_PAGAMENTO_REALIZADO DATE,
    PGM_DATA_DE_PAGAMENTO DATE NOT NULL,
    PGM_SALARIO DOUBLE(8,2) NOT NULL,
    PGM_VALOR_COMISSAO DOUBLE(8,2) NOT NULL,
    PGM_VALOR_TOTAL DOUBLE(8,2) NOT NULL,
    FK_MEDICOS_MED_ID INTEGER
);

CREATE TABLE DEPENDENTES (
    DPN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DPN_NOME VARCHAR(100) NOT NULL,
    DPN_DATA_NASCIMENTO DATE NOT NULL,
    FK_PACIENTES_PAC_ID INTEGER
);

CREATE TABLE VALORES_DEPENDENTES (
    VDP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VDP_VALOR DOUBLE(6,2) NOT NULL,
    VDP_IDADE_MINIMA INTEGER(3) NOT NULL,
    VDP_IDADE_MAXIMA INTEGER(3) NOT NULL,
    FK_PLANOS_PLN_ID INTEGER
);

CREATE TABLE USO_REMEDIO (
    FK_FINALIDADE_REMEDIOS_FIN_ID INTEGER,
    FK_REMEDIOS_RMD_ID INTEGER,
    URM_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE ESPECIALISTAS (
    FK_ESPECIALIDADES_MEDICAS_ESM_ID INTEGER,
    FK_MEDICOS_MED_ID INTEGER,
    ESP_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE PLANOS_BENEFICIOS (
    FK_BENEFICIOS_BNF_ID INTEGER,
    FK_PLANOS_PLN_ID INTEGER,
    PBN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PBN_VALOR_BENEFICIO INTEGER(4) NOT NULL
);

CREATE TABLE REMEDIO_PRESCRICAO (
    FK_REMEDIOS_RMD_ID INTEGER,
    FK_PRESCRICOES_PRE_ID INTEGER,
    RMP_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE FORMAS_FARMACEUTICAS (
    FRM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FRM_DESCRICAO VARCHAR(100) NOT NULL UNIQUE
);
 
ALTER TABLE REMEDIOS ADD CONSTRAINT FK_REMEDIOS_2
    FOREIGN KEY (FK_FORMAS_FARMACEUTICAS_FRM_ID)
    REFERENCES FORMAS_FARMACEUTICAS (FRM_ID);
 
ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTES_2
    FOREIGN KEY (FK_PLANOS_PLN_ID)
    REFERENCES PLANOS (PLN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EXAMES ADD CONSTRAINT FK_EXAMES_2
    FOREIGN KEY (FK_MEDICOS_MED_ID)
    REFERENCES MEDICOS (MED_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EXAMES ADD CONSTRAINT FK_EXAMES_3
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PAGAMENTOS ADD CONSTRAINT FK_PAGAMENTOS_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PRESCRICOES ADD CONSTRAINT FK_PRESCRICOES_2
    FOREIGN KEY (FK_MEDICOS_MED_ID)
    REFERENCES MEDICOS (MED_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PRESCRICOES ADD CONSTRAINT FK_PRESCRICOES_3
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PAGAMENTOS_MEDICOS ADD CONSTRAINT FK_PAGAMENTOS_MEDICOS_2
    FOREIGN KEY (FK_MEDICOS_MED_ID)
    REFERENCES MEDICOS (MED_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DEPENDENTES ADD CONSTRAINT FK_DEPENDENTES_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE VALORES_DEPENDENTES ADD CONSTRAINT FK_VALORES_DEPENDENTES_2
    FOREIGN KEY (FK_PLANOS_PLN_ID)
    REFERENCES PLANOS (PLN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE USO_REMEDIO ADD CONSTRAINT FK_USO_REMEDIO_2
    FOREIGN KEY (FK_FINALIDADE_REMEDIOS_FIN_ID)
    REFERENCES FINALIDADE_REMEDIOS (FIN_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE USO_REMEDIO ADD CONSTRAINT FK_USO_REMEDIO_3
    FOREIGN KEY (FK_REMEDIOS_RMD_ID)
    REFERENCES REMEDIOS (RMD_ID)
    ON DELETE SET NULL;
 
ALTER TABLE ESPECIALISTAS ADD CONSTRAINT FK_ESPECIALISTAS_2
    FOREIGN KEY (FK_ESPECIALIDADES_MEDICAS_ESM_ID)
    REFERENCES ESPECIALIDADES_MEDICAS (ESM_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE ESPECIALISTAS ADD CONSTRAINT FK_ESPECIALISTAS_3
    FOREIGN KEY (FK_MEDICOS_MED_ID)
    REFERENCES MEDICOS (MED_ID)
    ON DELETE SET NULL;
 
ALTER TABLE PLANOS_BENEFICIOS ADD CONSTRAINT FK_PLANOS_BENEFICIOS_2
    FOREIGN KEY (FK_BENEFICIOS_BNF_ID)
    REFERENCES BENEFICIOS (BNF_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE PLANOS_BENEFICIOS ADD CONSTRAINT FK_PLANOS_BENEFICIOS_3
    FOREIGN KEY (FK_PLANOS_PLN_ID)
    REFERENCES PLANOS (PLN_ID)
    ON DELETE SET NULL;
 
ALTER TABLE REMEDIO_PRESCRICAO ADD CONSTRAINT FK_REMEDIO_PRESCRICAO_2
    FOREIGN KEY (FK_REMEDIOS_RMD_ID)
    REFERENCES REMEDIOS (RMD_ID)
    ON DELETE SET NULL;
 
ALTER TABLE REMEDIO_PRESCRICAO ADD CONSTRAINT FK_REMEDIO_PRESCRICAO_3
    FOREIGN KEY (FK_PRESCRICOES_PRE_ID)
    REFERENCES PRESCRICOES (PRE_ID)
    ON DELETE SET NULL;
	
/* Inserts */
INSERT INTO formas_farmaceuticas ( FRM_DESCRICAO) VALUES ( "Adesivo Transdérmico" ),
	( "Aerosol" ),
	( "Aerosol Bucal" ),
	( "Aerosol Nasal" ),
	( "Aerosol Oral" ),
	( "Cápsula" ),
	( "Cápsula De Liberação Controlada" ),
	( "Cápsula De Liberação Prolongada" ),
	( "Cápsula Dura; Comrpimido; Comprimido Revestido" ),
	( "Cápsula Gelatinosa" ),
	( "Cápsula Gelatinosa Dura" ),
	( "Cápsula Gelatinosa Dura Entérica" ),
	( "Cápsula Gelatinosa Dura; Drágea; Comprimido" ),
	( "Cápsula Gelatinosa Mole" ),
	( "Cápsula Gelatinosa Mole; Comprimido Revestido De Liberação Prolongada" ),
	( "Cápsula Inalante" ),
	( "Cápsula Inalante; Aerosol Bucal" ),
	( "Cápsula Para Inalação" ),
	( "Cápsula; Comprimido" ),
	( "Colutório" ),
	( "Comprimido" ),
	( "Comprimido ; Cápsula" ),
	( "Comprimido Desintegração Lenta" ),
	( "Comprimido Dispersível" ),
	( "Comprimido Liberação Controlada" ),
	( "Comprimido Liberação Lenta" ),
	( "Comprimido Liberação Prolongada" ),
	( "Comprimido Mastigável" ),
	( "Comprimido Revestido" ),
	( "Comprimido Sublinga" ),
	( "Creme" ),
	( "Creme Vaginal" ),
	( "Drágea" ),
	( "Elixir" ),
	( "Emulasão ; Solução Oral" ),
	( "Emulsão" ),
	( "Enema" ),
	( "Envelope (Pó)" ),
	( "Frasco" ),
	( "Frasco-Ampola" ),
	( "Gel" ),
	( "Gel Oral" ),
	( "Gel Vaginal" ),
	( "Geléia" ),
	( "Goma De Mascar Ou Pastilha" ),
	( "Injeção Intravitrea" ),
	( "Injetável" ),
	( "Loção" ),
	( "Ovulo" ),
	( "Pastilha" ),
	( "Pó" ),
	( "Pó Efervescente" ),
	( "Pó Inalante" ),
	( "Pó Liofilizado" ),
	( "Pó Liofilizado Injetável" ),
	( "Pó Liofilizado Para Solução Injetável" ),
	( "Pó Ou Cápsula Inalante" ),
	( "Pó Para Inalação Oral" ),
	( "Pó Para Solução Injetável" ),
	( "Pó Para Solução Injetável Intra Muscular" ),
	( "Pó Para Solução Injetável Intravenoso" ),
	( "Pó Para Solução Oral" ),
	( "Pó Para Suspensão Injetável" ),
	( "Pó Para Suspensão Oral" ),
	( "Pó Tamponado Para Suspensão Oral + Solução Oral" ),
	( "Pomada" ),
	( "Pomada Oftálmica" ),
	( "Seringa" ),
	( "Shampoo" ),
	( "Solução Capilar" ),
	( "Solução Concentrada Para Infusão Intravenosa" ),
	( "Solução Injetável" ),
	( "Solução Nasal" ),
	( "Solução Oftálmica" ),
	( "Solução Oral" ),
	( "Solução Oral; Xarope" ),
	( "Solução Para Inalação" ),
	( "Solução Para Nebulização" ),
	( "Spray Nasal" ),
	( "Supositório" ),
	( "Supositório Adulto" ),
	( "Suspensão Injetavel" ),
	( "Suspensão Nasal" ),
	( "Suspensão Oftálmica" ),
	( "Suspensão Oral" ),
	( "Suspensão Tópica" ),
	( "Tintura" ),
	( "Tubete" ),
	( "Xarope" );