/* logico_mod2: */

CREATE TABLE AGENDAMENTOS (
    AGD_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    AGD_STATUS INTEGER NOT NULL,
    AGD_ENCAMINHAMENTOS BOOLEAN,
    AGD_DATA DATE NOT NULL,
    AGD_HORARIO TIME,
    AGD_MEET_LINK VARCHAR(255),
    AGD_RETORNO BOOLEAN,
    AGD_TRIAGEM_REALIZADA BOOLEAN,
    AGD_MOTIVO_ENCAMINHAMENTO VARCHAR(255),
    AGD_ENCAMINHAMENTO_PRESENCIAL BOOLEAN,
    FK_PACIENTES_PAC_ID INTEGER NOT NULL,
    FK_ESPECIALIDADES_MEDICAS_ESM_ID INTEGER NOT NULL,
    FK_MEDICOS_MED_ID INTEGER
);

CREATE TABLE CONSULTAS_ONLINE (
    CNS_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CNS_DATA DATE NOT NULL,
    CNS_ANOTACOES VARCHAR (255),
    CNS_SINTOMAS_IDENTIFICADOS VARCHAR(255),
    CNS_DIAGNOSTICO VARCHAR(250),
    FK_AGENDAMENTOS_AGD_ID INTEGER NOT NULL
);

CREATE TABLE MEDICOS (
    MED_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE TRIAGENS (
    TRG_SINTOMAS VARCHAR (255) NOT NULL,
    TRG_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TRG_TABELA_DOR INTEGER,
    TRG_PRESSAO_SISTOLICA INTEGER,
    TRG_TEMPERATURA DOUBLE,
    TRG_PRESSAO_DIASTOLICA INTEGER,
    FK_AGENDAMENTOS_AGD_ID INTEGER
);

CREATE TABLE PRESCRICOES (
    PRC_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRC_DURACAO_TRATAMENTO VARCHAR (60),
    PRC_OBSERVACOES VARCHAR (500),
    PRC_ASSINATURA_MEDICO BLOB NOT NULL,
    PRC_DATA_EMISSAO DATE NOT NULL,
    FK_CONSULTAS_ONLINE_CNS_ID INTEGER NOT NULL
);

CREATE TABLE REMEDIOS (
    RMD_TIPO INTEGER,
    RMD_INDICACOES VARCHAR(200),
    RMD_DOSAGEM INTEGER NOT NULL,
    RMD_NOME VARCHAR (100) NOT NULL UNIQUE,
    RMD_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    RMD_VIA_DOSAGEM INTEGER,
    RMD_CONTRA_INDICACAO VARCHAR(200),
    RMD_DISPONIVEL BOOLEAN,
    RMD_QUANTIDADE INTEGER
);

CREATE TABLE PACIENTES (
    PAC_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PAC_EMAIL VARCHAR(200),
    PAC_STATUS BOOLEAN
);

CREATE TABLE ESPECIALIDADES_MEDICAS (
    ESM_DESCRICAO VARCHAR(200) NOT NULL,
    ESM_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE REMEDIOS_PRESCRICOES (
    FK_REMEDIOS_RMD_ID INTEGER NOT NULL,
    FK_PRESCRICOES_PRC_ID INTEGER NOT NULL,
    PRM_ESQUEMA_POSOLOGICO VARCHAR(200) NOT NULL,
    PRM_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);
 
ALTER TABLE AGENDAMENTOS ADD CONSTRAINT FK_AGENDAMENTOS_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE AGENDAMENTOS ADD CONSTRAINT FK_AGENDAMENTOS_3
    FOREIGN KEY (FK_ESPECIALIDADES_MEDICAS_ESM_ID)
    REFERENCES ESPECIALIDADES_MEDICAS (ESM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE AGENDAMENTOS ADD CONSTRAINT FK_AGENDAMENTOS_4
    FOREIGN KEY (FK_MEDICOS_MED_ID)
    REFERENCES MEDICOS (MED_ID)
    ON DELETE SET NULL;
 
ALTER TABLE CONSULTAS_ONLINE ADD CONSTRAINT FK_CONSULTAS_ONLINE_2
    FOREIGN KEY (FK_AGENDAMENTOS_AGD_ID)
    REFERENCES AGENDAMENTOS (AGD_ID)
    ON DELETE CASCADE;
 
ALTER TABLE TRIAGENS ADD CONSTRAINT FK_TRIAGENS_2
    FOREIGN KEY (FK_AGENDAMENTOS_AGD_ID)
    REFERENCES AGENDAMENTOS (AGD_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PRESCRICOES ADD CONSTRAINT FK_PRESCRICOES_2
    FOREIGN KEY (FK_CONSULTAS_ONLINE_CNS_ID)
    REFERENCES CONSULTAS_ONLINE (CNS_ID)
    ON DELETE CASCADE;
 
ALTER TABLE REMEDIOS_PRESCRICOES ADD CONSTRAINT FK_REMEDIOS_PRESCRICOES_2
    FOREIGN KEY (FK_REMEDIOS_RMD_ID)
    REFERENCES REMEDIOS (RMD_ID)
    ON DELETE CASCADE;
 
ALTER TABLE REMEDIOS_PRESCRICOES ADD CONSTRAINT FK_REMEDIOS_PRESCRICOES_3
    FOREIGN KEY (FK_PRESCRICOES_PRC_ID)
    REFERENCES PRESCRICOES (PRC_ID)
    ON DELETE CASCADE;