/* ModeloLógico_Sprint02: */

CREATE TABLE ENFERMEIROS (
    ENF_ID INTEGER,
    FK_FUNCIONARIOS_FUN_ID INTEGER,
    FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INTEGER,
    PRIMARY KEY (ENF_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE MEDICOS (
    MED_ID INTEGER,
    FK_FUNCIONARIOS_FUN_ID INTEGER,
    FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INTEGER,
    PRIMARY KEY (MED_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE FUNCIONARIOS (
    FUN_ID INTEGER,
    FUN_PRONTUARIO VARCHAR(8),
    FUN_CATEGORIA INTEGER,
    FK_USUARIO_COMUM_USC_ID INTEGER,
    PRIMARY KEY (FUN_ID, FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE DEPENDENTES (
    DEP_NV_PARENTESCO INTEGER,
    DEP_ID INTEGER,
    FK_PACIENTES_PAC_ID INTEGER,
    FK_PACIENTES_FK_USUARIO_COMUM_USC_ID INTEGER,
    FK_RESPONSAVEIS_RES_ID INTEGER,
    FK_RESPONSAVEIS_FK_PACIENTES_PAC_ID INTEGER,
    FK_RESPONSAVEIS_FK_PACIENTES_FK_USUARIO_COMUM_USC_ID INTEGER,
    PRIMARY KEY (DEP_ID, FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE USUARIO_COMUM (
    USC_ORGAO_EMISSOR VARCHAR(10),
    USC_ID INTEGER PRIMARY KEY,
    USC_RG VARCHAR(15),
    USC_CPF VARCHAR(20),
    USC_DATA_NASCIMENTO DATE,
    USC_SENHA VARCHAR(200),
    USC_SEXO INTEGER,
    USC_NOME VARCHAR(180),
    USC_ESTADO INTEGER,
    USC_CIDADE VARCHAR(100),
    USC_BAIRRO VARCHAR(100),
    USC_NUMERO VARCHAR(10),
    USC_LOGRADOURO VARCHAR(200),
    USC_HASH_REC VARCHAR(32),
    USC_UPDATED_AT DATETIME
);

CREATE TABLE PACIENTES (
    PAC_ID INTEGER,
    PAC_EMAIL VARCHAR(200),
    PAC_STATUS BOOLEAN,
    FK_USUARIO_COMUM_USC_ID INTEGER,
    PRIMARY KEY (PAC_ID, FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE RESPONSAVEIS (
    RES_TEM_ALERGIA_MEDICA BOOLEAN,
    RES_QTD_FILHOS INTEGER,
    RES_QUAIS_ALERGIAS VARCHAR(200),
    RES_TEL_CELULAR1 VARCHAR(20),
    RES_TEL_CELULAR2 VARCHAR(20),
    RES_QUAL_MEDICACAO VARCHAR(200),
    RES_QUAIS_TRAT_MED VARCHAR(200),
    RES_TEM_FILHOS BOOLEAN,
    RES_UTILIZA_MEDICACAO BOOLEAN,
    RES_ID INTEGER,
    FK_PACIENTES_PAC_ID INTEGER,
    FK_PACIENTES_FK_USUARIO_COMUM_USC_ID INTEGER,
    PRIMARY KEY (RES_ID, FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE CONTABILIDADE (
    CON_ID INTEGER,
    FK_FUNCIONARIOS_FUN_ID INTEGER,
    FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INTEGER,
    PRIMARY KEY (CON_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE ADMINISTRATIVO (
    ADM_ID INTEGER,
    ADM_FUNCAO INTEGER,
    ADM_DATA_ADMISSAO DATE,
    ADM_DATA_DEMISSAO DATE,
    ADM_CLINICA INTEGER,
    ADM_SALARIO FLOAT,
    ADM_CRM VARCHAR(20),
    ADM_TELEFONE_CELULAR VARCHAR(20),
    FK_FUNCIONARIOS_FUN_ID INTEGER,
    FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INTEGER,
    PRIMARY KEY (ADM_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE CONTATOS_SETORIAIS (
    CSE_ID INTEGER PRIMARY KEY,
    CSE_SETOR VARCHAR(200),
    CSE_TELEFONE_FIXO VARCHAR(20),
    CSE_EMAIL VARCHAR(200),
    CSE_TELEFONE_CELULAR VARCHAR(20)
);
 
ALTER TABLE ENFERMEIROS ADD CONSTRAINT FK_ENFERMEIROS_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES FUNCIONARIOS (FUN_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE MEDICOS ADD CONSTRAINT FK_MEDICOS_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES FUNCIONARIOS (FUN_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE FUNCIONARIOS ADD CONSTRAINT FK_FUNCIONARIOS_2
    FOREIGN KEY (FK_USUARIO_COMUM_USC_ID)
    REFERENCES USUARIO_COMUM (USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DEPENDENTES ADD CONSTRAINT FK_DEPENDENTES_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    REFERENCES PACIENTES (PAC_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DEPENDENTES ADD CONSTRAINT FK_DEPENDENTES_3
    FOREIGN KEY (FK_RESPONSAVEIS_RES_ID, FK_RESPONSAVEIS_FK_PACIENTES_PAC_ID, FK_RESPONSAVEIS_FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    REFERENCES RESPONSAVEIS (RES_ID, FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTES_2
    FOREIGN KEY (FK_USUARIO_COMUM_USC_ID)
    REFERENCES USUARIO_COMUM (USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RESPONSAVEIS ADD CONSTRAINT FK_RESPONSAVEIS_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    REFERENCES PACIENTES (PAC_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONTABILIDADE ADD CONSTRAINT FK_CONTABILIDADE_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES FUNCIONARIOS (FUN_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ADMINISTRATIVO ADD CONSTRAINT FK_ADMINISTRATIVO_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES FUNCIONARIOS (FUN_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;