INSERT INTO `finalidade_remedios` (`FIN_DESCRICAO`, `FIN_ID`) VALUES 
('dor de cabeça', NULL),
('febre', NULL),
('tranquilizante', NULL),
('antibiótico', NULL);

INSERT INTO `remedios` (`RMD_ID`, `RMD_NOME`, `RMD_VIA_DOSAGEM`, `FK_FORMAS_FARMACEUTICAS_FRM_ID`, `RMD_INDICACAO`, `RMD_CONTRAINDICACAO`, `RMD_DOSAGEM`) VALUES (NULL, 'Paracetamol', '1', '21', 'Paracetamol é um analgésico e antipirético, sendo indicado para a alívio da dor de intensidade leve a moderada, incluindo dor de cabeça, enxaqueca, dor músculo esquelética, cólicas menstruais, dor de garganta, dor de dente, dor pós-procedimentos odontológicos, dor e febre após vacinação, e dor de osteoartrite.', 'Este medicamento não deve ser usado em caso de hipersensibilidade ao paracetamol ou a qualquer outro componente da fórmula.\r\n\r\nNão use qualquer outro produto que contenha paracetamol.', '4000');

INSERT INTO `remedios` (`RMD_ID`, `RMD_NOME`, `RMD_VIA_DOSAGEM`, `FK_FORMAS_FARMACEUTICAS_FRM_ID`, `RMD_INDICACAO`, `RMD_CONTRAINDICACAO`, `RMD_DOSAGEM`) VALUES (NULL, 'Clonazepam (Rivotril)', '1', '21', 'Uso adulto e pediátrico\r\n\r\nDistúrbio epiléptico\r\n\r\nRivotril® é indicado para tratar crises epilépticas e espasmos infantis (Síndrome de West).\r\nUso adulto\r\n\r\nRivotril® também é indicado para:\r\n\r\nTranstornos de ansiedade\r\n\r\nComo ansiolítico em geral;\r\nDistúrbio do pânico com ou sem medo de espaços abertos;\r\nFobia social (medo de situações como falar em público).\r\nTranstornos do humor\r\n\r\nTranstorno afetivo bipolar (fases de depressão e mania): tratamento da mania;\r\nDepressão maior: associado a antidepressivos na depressão ansiosa e início do tratamento.\r\nSíndromes psicóticas\r\n\r\nAcatisia (inquietação extrema, geralmente provocada por medicamentos psiquiátricos);\r\nSíndrome das pernas inquietas\r\n\r\nDesconforto ou dor nas pernas que leva a necessidade de movimentá-las, prejudicando o sono.\r\nVertigem e distúrbios do equilíbrio\r\n\r\nNáuseas, vômitos, desmaios, quedas, zumbidos e distúrbios auditivos.\r\nSíndrome da boca ardente\r\n\r\nSensação de queimação na parte interna da boca, sem alterações físicas.', 'Rivotril® é contraindicado a pacientes com hipersensibilidade conhecida a clonazepam ou a qualquer dos excipientes do medicamento, em pacientes com insuficiência respiratória grave ou comprometimento do fígado grave, pois os benzodiazepínicos podem levar à ocorrência de comprometimento do sistema nervoso, secundário ao problema no fígado.\r\n\r\nRivotril® comprimidos e Rivotril® gotas são contraindicados para o tratamento de transtornos do pânico em pacientes com histórico médico de apneia do sono.\r\n\r\nRivotril® é contraindicado a pacientes com glaucoma agudo de ângulo fechado. Rivotril® pode ser usado por pacientes com glaucoma de ângulo aberto, desde que estejam recebendo terapia apropriada.', '6');

INSERT INTO `remedios` (`RMD_ID`, `RMD_NOME`, `RMD_VIA_DOSAGEM`, `FK_FORMAS_FARMACEUTICAS_FRM_ID`, `RMD_INDICACAO`, `RMD_CONTRAINDICACAO`, `RMD_DOSAGEM`) VALUES (NULL, 'Penicilina G Benzatina', '6', '39', 'Indicada para combater diversos tipos de bactérias, a penicilina é comumente usada em casos de:\r\n\r\ninfecção de garganta (faringite, amigdalite);\r\nouvido (otite);\r\nsinusite;\r\npneumonia.\r\nAlém disso, é usada no tratamento de algumas Doenças Sexualmente Transmissíveis (DSTs), como a sífilis.', 'A penicilina benzatina não deve ser administrada em pacientes com história de alergia à penicilina.\r\n\r\nO Benzetacil pode ser usado na gravidez, caso necessário. Porém, assim como qualquer outro fármaco, o seu uso nas grávidas deve ser bem criterioso.\r\n\r\nO mesmo raciocínio se aplica durante a fase aleitamento materno. A penicilina benzatina não corta o leite nem faz mal ao bebê, mas se puder ser evitada, melhor.\r\n\r\nO Benzetacil pode ser administrado em mulheres que fazem uso de anticoncepcional hormonal, já que não há estudos que indiquem a redução do efeito da pílula', '4');

INSERT INTO `uso_remedio` (`FK_FINALIDADE_REMEDIOS_FIN_ID`, `FK_REMEDIOS_RMD_ID`, `URM_ID`) VALUES ('4', '3', NULL);

INSERT INTO `uso_remedio` (`FK_FINALIDADE_REMEDIOS_FIN_ID`, `FK_REMEDIOS_RMD_ID`, `URM_ID`) VALUES ('1', '1', NULL);

INSERT INTO `uso_remedio` (`FK_FINALIDADE_REMEDIOS_FIN_ID`, `FK_REMEDIOS_RMD_ID`, `URM_ID`) VALUES ('2', '1', NULL);

INSERT INTO `uso_remedio` (`FK_FINALIDADE_REMEDIOS_FIN_ID`, `FK_REMEDIOS_RMD_ID`, `URM_ID`) VALUES ('3', '2', NULL);

