INSERT INTO `triagens` (`TRG_SINTOMAS`, `TRG_ID`, `TRG_TABELA_DOR`, `TRG_PRESSAO_SISTOLICA`, `TRG_TEMPERATURA`, `TRG_PRESSAO_DIASTOLICA`, `FK_AGENDAMENTOS_AGD_ID`) VALUES ('Dor de Cabeca, Coriza, Febre', NULL, '9', '36', '38.8', '34', '2');

INSERT INTO `consultas_online` (`CNS_ID`, `CNS_DATA`, `CNS_ANOTACOES`, `CNS_SINTOMAS_IDENTIFICADOS`, `CNS_DIAGNOSTICO`, `FK_AGENDAMENTOS_AGD_ID`, `FK_MEDICOS_MED_ID`, `FK_PACIENTES_PAC_ID`) VALUES (NULL, '2022-08-12', 'Paciente com muita dor nas costas', 'Dor nas costas e incomodo ao andar ', 'Paciente possui hérnia de disco', '2', '1', '2');

INSERT INTO `agendamentos` (`AGD_ID`, `AGD_STATUS`, `AGD_ENCAMINHAMENTOS`, `AGD_DATA`, `AGD_HORARIO`, `AGD_MEET_LINK`, `FK_PACIENTES_PAC_ID`, `FK_TIPOS_ESPECIALIDADES_MEDICAS_TEM_ID`, `FK_MEDICOS_MED_ID`, `AGD_TRIAGEM_REALIZADA`, `AGD_RETORNO`) VALUES (NULL, '1', '1', '2022-08-11', '19:51:10', NULL, '2', '2', NULL, '1', '1');

INSERT INTO `consultas_online` (`CNS_ID`, `CNS_DATA`, `CNS_ANOTACOES`, `CNS_SINTOMAS_IDENTIFICADOS`, `CNS_DIAGNOSTICO`, `FK_AGENDAMENTOS_AGD_ID`, `FK_MEDICOS_MED_ID`, `FK_PACIENTES_PAC_ID`) VALUES (NULL, '2022-08-11', NULL, 'Nenhum sintoma identificado', 'Nenhum diagnostico identificado', '2', '1', '2');

