--UC09-Visualizar Detalhes da Consulta
INSERT INTO `pacientes` (`PAC_ID`, `PAC_NOME_COMPLETO`) VALUES (2, 'Jose Batista Andrade de Pinheiro');

INSERT INTO `tipos_especialidades_medicas` (`TEM_ID`, `TEM_NOME_ESPECIALIDADE`) VALUES (1, 'Clínico Geral');

INSERT INTO `agendamentos` (`AGD_ID`, `AGD_STATUS`, `AGD_ENCAMINHAMENTOS`, `AGD_DATA`, `AGD_HORARIO`, `AGD_MEET_LINK`, `FK_PACIENTES_PAC_ID`, `FK_TIPOS_ESPECIALIDADES_MEDICAS_TEM_ID`, `FK_MEDICOS_MED_ID`, `AGD_TRIAGEM_REALIZADA`, `AGD_RETORNO`) VALUES (NULL, '1', '0', '2022-07-15', NULL, NULL, '1', '1', '1', '0', '0');

INSERT INTO `consultas_online` (`CNS_ID`, `CNS_DATA`, `CNS_ANOTACOES`, `CNS_SINTOMAS_IDENTIFICADOS`, `CNS_DIAGNOSTICO`, `FK_AGENDAMENTOS_AGD_ID`, `FK_MEDICOS_MED_ID`, `FK_PACIENTES_PAC_ID`) VALUES (NULL, '2022-07-15', NULL, 'N/a', 'N/a', '1', '1', '1');

--UC08-Listar Consultas Solicitadas
INSERT INTO `tipos_especialidades_medicas` (`TEM_ID`, `TEM_NOME_ESPECIALIDADE`) VALUES (2, 'Ginecologista'), (3, 'Pediatra');

INSERT INTO `pacientes` (`PAC_ID`, `PAC_NOME_COMPLETO`) VALUES (2, 'Jose Maria Marcos Antonio');

INSERT INTO `pacientes` (`PAC_ID`, `PAC_NOME_COMPLETO`) VALUES (3, 'Maria Jose Marcos Antonio');

INSERT INTO `pacientes` (`PAC_ID`, `PAC_NOME_COMPLETO`) VALUES (4, 'Edmundo Matias Evaristo');

INSERT INTO `agendamentos` (`AGD_ID`, `AGD_STATUS`, `AGD_ENCAMINHAMENTOS`, `AGD_DATA`, `AGD_HORARIO`, `AGD_MEET_LINK`, `FK_PACIENTES_PAC_ID`, `FK_TIPOS_ESPECIALIDADES_MEDICAS_TEM_ID`, `FK_MEDICOS_MED_ID`, `AGD_TRIAGEM_REALIZADA`, `AGD_RETORNO`) VALUES (NULL, '0', '0', '2022-07-18', NULL, NULL, '2', '1', '1', '0', '0');

INSERT INTO `agendamentos` (`AGD_ID`, `AGD_STATUS`, `AGD_ENCAMINHAMENTOS`, `AGD_DATA`, `AGD_HORARIO`, `AGD_MEET_LINK`, `FK_PACIENTES_PAC_ID`, `FK_TIPOS_ESPECIALIDADES_MEDICAS_TEM_ID`, `FK_MEDICOS_MED_ID`, `AGD_TRIAGEM_REALIZADA`, `AGD_RETORNO`) VALUES (NULL, '1', '0', '2022-07-19', NULL, NULL, '3', '2', '1', '0', '0');

INSERT INTO `agendamentos` (`AGD_ID`, `AGD_STATUS`, `AGD_ENCAMINHAMENTOS`, `AGD_DATA`, `AGD_HORARIO`, `AGD_MEET_LINK`, `FK_PACIENTES_PAC_ID`, `FK_TIPOS_ESPECIALIDADES_MEDICAS_TEM_ID`, `FK_MEDICOS_MED_ID`, `AGD_TRIAGEM_REALIZADA`, `AGD_RETORNO`) VALUES (NULL, '1', '0', '2022-07-20', NULL, NULL, '4', '3', '1', '0', '0');