/* Modelo Fisico Modulo 03 Sprint #02: */

CREATE TABLE RESPONSAVEIS (
    RES_ID INT(3) PRIMARY KEY,
    RES_QTD_FILHOS INT,
    RES_QUAIS_TRAT_MED VARCHAR(200),
    RES_TEM_ALERGIA_MEDICA BOOLEAN,
    RES_QUAL_MEDICACAO VARCHAR(200),
    RES_QUAIS_ALERGIAS VARCHAR(200),
    RES_TEL_CELULAR1 VARCHAR(20),
    RES_UTILIZA_MEDICACAO BOOLEAN,
    RES_TEL_CELULAR2 VARCHAR(20),
    RES_TEM_FILHOS BOOLEAN,
    RES_QUAIS_DOENCAS_CRONICAS VARCHAR(200),
    RES_TRATAMENTO_MEDICO BOOLEAN,
    RES_DOENCAS_CRONICAS BOOLEAN,
    FK_PACIENTES_PAC_ID INT(3)
);

CREATE TABLE USUARIO_COMUM (
    USC_ID INT(3) PRIMARY KEY,
    USC_NOME VARCHAR(100),
    USC_SEXO INT,
    USC_CIDADE VARCHAR(100),
    USC_BAIRRO VARCHAR(100),
    USC_DATA_NASCIMENTO DATE,
    USC_ESTADO INT,
    USC_SENHA VARCHAR(200),
    USC_ORGAO_EMISSOR VARCHAR(10),
    USC_CPF VARCHAR(20),
    USC_RG VARCHAR(15),
    USC_LOGRADOURO VARCHAR(200),
    USC_NUMERO VARCHAR(10)
);

CREATE TABLE FINALIDADE_REMEDIOS (
    FIN_ID INT(3) PRIMARY KEY,
    FIN_DESCRICAO VARCHAR(100)
);

CREATE TABLE PAGAMENTOS_MEDICOS (
    PGM_ID INT(3) PRIMARY KEY,
    PGM_DATA_PAGAMENTO DATE,
    PGM_SALARIO DOUBLE(8,2),
    PGM_VALOR_COMISSAO DOUBLE(8,2),
    PGM_VALOR_TOTAL DOUBLE(8,2),
    PGM_DATA_PAGAMENTO_REALIZADO DATE,
    PGM_CONSULTAS_MES INT,
    FK_MEDICOS_MED_ID INT(3)
);

CREATE TABLE FUNCIONARIOS (
    FUN_ID INT(3) PRIMARY KEY,
    FUN_PRONTUARIO VARCHAR(8),
    FUN_CATEGORIA VARCHAR(20),
    FK_USUARIO_COMUM_USC_ID INT(3)
);

CREATE TABLE CONTABILIDADE (
    CON_ID INT(3) PRIMARY KEY,
    FK_FUNCIONARIOS_FUN_ID INT(3)
);

CREATE TABLE PACIENTES (
    PAC_ID INT(3) PRIMARY KEY,
    PAC_EMAIL VARCHAR(200),
    PAC_STATUS BOOLEAN,
    FK_PLANOS_PLN_ID INT(3),
    FK_USUARIO_COMUM_USC_ID INT(3)
);

CREATE TABLE EXAMES (
    EXM_ID INT PRIMARY KEY,
    EXM_NOME VARCHAR(100),
    EXM_ANEXO_GUIA BLOB,
    EXM_OBS_SECRETARIO VARCHAR(200),
    EXM_AGENDAMENTO VARCHAR(50),
    EXM_AUTORIZADO BOOLEAN,
    EXM_ANEXO_RESULTADO BLOB,
    EXM_OBS_PACIENTE VARCHAR(200),
    FK_PACIENTES_PAC_ID INT(3),
    FK_MEDICOS_MED_ID INT(3)
);

CREATE TABLE DEPENDENTES (
    DEP_ID INT(3) PRIMARY KEY,
    DEP_NOME VARCHAR(100),
    DEP_NV_PARENTESCO INT,
    DEP_DATA_NASCIMENTO DATE,
    FK_RESPONSAVEIS_RES_ID INT(3),
    FK_PACIENTES_PAC_ID INT(3)
);

CREATE TABLE TRIAGENS (
    TRG_ID INT(3) PRIMARY KEY,
    TRG_SINTOMAS VARCHAR(255),
    TRG_TABELA_DOR INT,
    TRG_PRESSAO_SISTOLICA INT,
    TRG_TEMPERATURA DOUBLE,
    TRG_PRESSAO_DIASTOLICA INT,
    FK_AGENDAMENTOS_AGD_ID INT(3)
);

CREATE TABLE CLINICAS_MEDICAS (
    CLI_ID INT(3) PRIMARY KEY,
    CLI_RAZAO_SOCIAL VARCHAR(200),
    CLI_CONTATO1 VARCHAR(20),
    CLI_CONTATO2 VARCHAR(20),
    CLI_DATA_FUNDACAO DATE,
    CLI_CNPJ VARCHAR(30),
    FK_ADMINISTRATIVO_ADM_ID INT(3)
);

CREATE TABLE MEDICOS (
    MED_ID INT(3) PRIMARY KEY,
    FK_FUNCIONARIOS_FUN_ID INT(3)
);

CREATE TABLE AGENDAMENTOS (
    AGD_ID INT(3) PRIMARY KEY,
    AGD_STATUS INT,
    AGD_ENCAMINHAMENTOS BOOLEAN,
    AGD_DATA DATE,
    AGD_HORARIO TIME,
    AGD_MEET_LINK VARCHAR(255),
    FK_MEDICOS_MED_ID INT(3),
    FK_ESPECIALIDADES_MEDICAS_ESM_ID INT,
    FK_PACIENTES_PAC_ID INT(3)
);

CREATE TABLE ESPECIALIDADES_MEDICAS (
    ESM_ID INT PRIMARY KEY,
    ESM_DESCRICAO VARCHAR(200)
);

CREATE TABLE BENEFICIOS (
    BNF_ID INT(3) PRIMARY KEY,
    BNF_DESCRICAO VARCHAR(100)
);

CREATE TABLE PAGAMENTOS (
    PGD_ID INT(3) PRIMARY KEY,
    PGD_VENCIMENTO DATE,
    PGD_DATA_PAGAMENTO DATE,
    PGD_VALOR_TOTAL DOUBLE(8,2),
    PGD_QUANTIDADE_DEPENDENTES INT,
    FK_PACIENTES_PAC_ID INT(3)
);

CREATE TABLE CONSULTAS_ONLINE (
    CNS_ID INT(3) PRIMARY KEY,
    CNS_DATA DATE,
    CNS_ANOTACOES VARCHAR(255),
    CNS_SINTOMAS_IDENTIFICADOS VARCHAR(255),
    CNS_DIAGNOSTICO VARCHAR(255),
    FK_AGENDAMENTOS_AGD_ID INT(3)
);

CREATE TABLE ENFERMEIROS (
    ENF_ID INT(3) PRIMARY KEY,
    FK_FUNCIONARIOS_FUN_ID INT(3)
);

CREATE TABLE REMEDIOS (
    RMD_ID INT(3) PRIMARY KEY,
    RMD_NOME VARCHAR(100),
    RMD_VIA_DOSAGEM INT,
    RMD_INDICACAO TEXT,
    RMD_CONTRAINDICACAO TEXT,
    RMD_DOSAGEM INT(4),
    FK_FORMAS_FARMACEUTICAS_FRM_ID INT(3)
);

CREATE TABLE CONTATOS_SETORIAIS (
    CSE_ID INT(3) PRIMARY KEY,
    CSE_TELEFONE_CELULAR VARCHAR(20),
    CSE_TELEFONE_FIXO VARCHAR(20),
    CSE_SETOR VARCHAR(200),
    CSE_EMAIL VARCHAR(200)
);

CREATE TABLE ADMINISTRATIVO (
    ADM_ID INT(3) PRIMARY KEY,
    ADM_FUNCAO INT,
    ADM_DATA_ADMISSAO DATE,
    ADM_DATA_DEMISSAO DATE,
    ADM_CLINICA INT,
    ADM_SALARIO FLOAT,
    ADM_CRM VARCHAR(20),
    ADM_TELEFONE_CELULAR VARCHAR(20),
    FK_FUNCIONARIOS_FUN_ID INT(3)
);

CREATE TABLE VALORES_DEPENDENTES (
    VPD_ID INT(3) PRIMARY KEY,
    VPD_IDADE_MAXIMA INT(3),
    VPD_IDADE_MINIMA INT(3),
    VPD_VALOR DOUBLE(6,2),
    FK_PLANOS_PLN_ID INT(3)
);

CREATE TABLE PLANOS (
    PLN_ID INT(3) PRIMARY KEY,
    PLN_NOME VARCHAR(100),
    PLN_INSTITUICAO VARCHAR(100),
    PLN_PRECO DOUBLE(6,2)
);

CREATE TABLE PRESCRICOES (
    PRC_ID INT(3) PRIMARY KEY,
    PRC_DURACAO_TRATAMENTO VARCHAR(60),
    PRC_OBSERVACOES VARCHAR(500),
    PRC_ASSINATURA_MEDICO VARCHAR(255),
    PRC_DATA_EMISSAO DATE,
    FK_MEDICOS_MED_ID INT(3),
    FK_CONSULTAS_ONLINE_CNS_ID INT(3)
);

CREATE TABLE FORMAS_FARMACEUTICAS (
    FRM_ID INT(3) PRIMARY KEY,
    FRM_DESCRICAO VARCHAR(100)
);

CREATE TABLE PLANOS_BENEFICIOS (
    FK_BENEFICIOS_BNF_ID INT(3),
    FK_PLANOS_PLN_ID INT(3),
    PBN_ID INT(3) PRIMARY KEY,
    PBN_VALOR_BENEFICIO INT(4)
);

CREATE TABLE USO_REMEDIO (
    FK_FINALIDADE_REMEDIOS_FIN_ID INT(3),
    FK_REMEDIOS_RMD_ID INT(3)
);

CREATE TABLE REMEDIOS_PRESCRICOES (
    FK_PRESCRICOES_PRC_ID INT(3),
    FK_REMEDIOS_RMD_ID INT(3),
    RMP_ID INT(3) PRIMARY KEY,
    RMP_ESQUEMA_POSOLOGICO VARCHAR(200)
);

CREATE TABLE ESPECIALISTAS (
    FK_ESPECIALIDADES_MEDICAS_ESM_ID INT,
    FK_MEDICOS_MED_ID INT(3),
    ESP_ID INT(3) PRIMARY KEY
);
 
ALTER TABLE RESPONSAVEIS ADD CONSTRAINT FK_RESPONSAVEIS_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PAGAMENTOS_MEDICOS ADD CONSTRAINT FK_PAGAMENTOS_MEDICOS_2
    FOREIGN KEY (FK_MEDICOS_MED_ID)
    REFERENCES MEDICOS (MED_ID)
    ON DELETE SET NULL;
 
ALTER TABLE FUNCIONARIOS ADD CONSTRAINT FK_FUNCIONARIOS_2
    FOREIGN KEY (FK_USUARIO_COMUM_USC_ID)
    REFERENCES USUARIO_COMUM (USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONTABILIDADE ADD CONSTRAINT FK_CONTABILIDADE_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID)
    REFERENCES FUNCIONARIOS (FUN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTES_2
    FOREIGN KEY (FK_PLANOS_PLN_ID)
    REFERENCES PLANOS (PLN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTES_3
    FOREIGN KEY (FK_USUARIO_COMUM_USC_ID)
    REFERENCES USUARIO_COMUM (USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EXAMES ADD CONSTRAINT FK_EXAMES_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EXAMES ADD CONSTRAINT FK_EXAMES_3
    FOREIGN KEY (FK_MEDICOS_MED_ID)
    REFERENCES MEDICOS (MED_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DEPENDENTES ADD CONSTRAINT FK_DEPENDENTES_2
    FOREIGN KEY (FK_RESPONSAVEIS_RES_ID)
    REFERENCES RESPONSAVEIS (RES_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DEPENDENTES ADD CONSTRAINT FK_DEPENDENTES_3
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE TRIAGENS ADD CONSTRAINT FK_TRIAGENS_2
    FOREIGN KEY (FK_AGENDAMENTOS_AGD_ID)
    REFERENCES AGENDAMENTOS (AGD_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CLINICAS_MEDICAS ADD CONSTRAINT FK_CLINICAS_MEDICAS_2
    FOREIGN KEY (FK_ADMINISTRATIVO_ADM_ID)
    REFERENCES ADMINISTRATIVO (ADM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE MEDICOS ADD CONSTRAINT FK_MEDICOS_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID)
    REFERENCES FUNCIONARIOS (FUN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE AGENDAMENTOS ADD CONSTRAINT FK_AGENDAMENTOS_2
    FOREIGN KEY (FK_MEDICOS_MED_ID)
    REFERENCES MEDICOS (MED_ID)
    ON DELETE SET NULL;
 
ALTER TABLE AGENDAMENTOS ADD CONSTRAINT FK_AGENDAMENTOS_3
    FOREIGN KEY (FK_ESPECIALIDADES_MEDICAS_ESM_ID)
    REFERENCES ESPECIALIDADES_MEDICAS (ESM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE AGENDAMENTOS ADD CONSTRAINT FK_AGENDAMENTOS_4
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PAGAMENTOS ADD CONSTRAINT FK_PAGAMENTOS_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONSULTAS_ONLINE ADD CONSTRAINT FK_CONSULTAS_ONLINE_2
    FOREIGN KEY (FK_AGENDAMENTOS_AGD_ID)
    REFERENCES AGENDAMENTOS (AGD_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ENFERMEIROS ADD CONSTRAINT FK_ENFERMEIROS_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID)
    REFERENCES FUNCIONARIOS (FUN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE REMEDIOS ADD CONSTRAINT FK_REMEDIOS_2
    FOREIGN KEY (FK_FORMAS_FARMACEUTICAS_FRM_ID)
    REFERENCES FORMAS_FARMACEUTICAS (FRM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ADMINISTRATIVO ADD CONSTRAINT FK_ADMINISTRATIVO_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID)
    REFERENCES FUNCIONARIOS (FUN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE VALORES_DEPENDENTES ADD CONSTRAINT FK_VALORES_DEPENDENTES_2
    FOREIGN KEY (FK_PLANOS_PLN_ID)
    REFERENCES PLANOS (PLN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PRESCRICOES ADD CONSTRAINT FK_PRESCRICOES_2
    FOREIGN KEY (FK_MEDICOS_MED_ID)
    REFERENCES MEDICOS (MED_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PRESCRICOES ADD CONSTRAINT FK_PRESCRICOES_3
    FOREIGN KEY (FK_CONSULTAS_ONLINE_CNS_ID)
    REFERENCES CONSULTAS_ONLINE (CNS_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PLANOS_BENEFICIOS ADD CONSTRAINT FK_PLANOS_BENEFICIOS_2
    FOREIGN KEY (FK_BENEFICIOS_BNF_ID)
    REFERENCES BENEFICIOS (BNF_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE PLANOS_BENEFICIOS ADD CONSTRAINT FK_PLANOS_BENEFICIOS_3
    FOREIGN KEY (FK_PLANOS_PLN_ID)
    REFERENCES PLANOS (PLN_ID)
    ON DELETE SET NULL;
 
ALTER TABLE USO_REMEDIO ADD CONSTRAINT FK_USO_REMEDIO_1
    FOREIGN KEY (FK_FINALIDADE_REMEDIOS_FIN_ID)
    REFERENCES FINALIDADE_REMEDIOS (FIN_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE USO_REMEDIO ADD CONSTRAINT FK_USO_REMEDIO_2
    FOREIGN KEY (FK_REMEDIOS_RMD_ID)
    REFERENCES REMEDIOS (RMD_ID)
    ON DELETE SET NULL;
 
ALTER TABLE REMEDIOS_PRESCRICOES ADD CONSTRAINT FK_REMEDIOS_PRESCRICOES_2
    FOREIGN KEY (FK_PRESCRICOES_PRC_ID)
    REFERENCES PRESCRICOES (PRC_ID)
    ON DELETE SET NULL;
 
ALTER TABLE REMEDIOS_PRESCRICOES ADD CONSTRAINT FK_REMEDIOS_PRESCRICOES_3
    FOREIGN KEY (FK_REMEDIOS_RMD_ID)
    REFERENCES REMEDIOS (RMD_ID)
    ON DELETE SET NULL;
 
ALTER TABLE ESPECIALISTAS ADD CONSTRAINT FK_ESPECIALISTAS_2
    FOREIGN KEY (FK_ESPECIALIDADES_MEDICAS_ESM_ID)
    REFERENCES ESPECIALIDADES_MEDICAS (ESM_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE ESPECIALISTAS ADD CONSTRAINT FK_ESPECIALISTAS_3
    FOREIGN KEY (FK_MEDICOS_MED_ID)
    REFERENCES MEDICOS (MED_ID)
    ON DELETE SET NULL;