/* Modelo_Logico: */

CREATE TABLE ENFERMEIROS (
    ENF_ID INT AUTO_INCREMENT,
    FK_FUNCIONARIOS_FUN_ID INT NOT NULL,
    FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INT NOT NULL,
    PRIMARY KEY (ENF_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE MEDICOS (
    MED_ID INT NOT NULL,
    FK_FUNCIONARIOS_FUN_ID INT NOT NULL,
    FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INT NOT NULL,
    PRIMARY KEY (MED_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE FUNCIONARIOS (
    FUN_ID INT AUTO_INCREMENT,
    FK_USUARIO_COMUM_USC_ID INT NOT NULL,
    PRIMARY KEY (FUN_ID, FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE DEPENDENTES (
    DEP_NV_PARENTESCO INT NOT NULL,
    DEP_ID INT AUTO_INCREMENT,
    FK_PACIENTES_PAC_ID INT NOT NULL,
    FK_PACIENTES_FK_USUARIO_COMUM_USC_ID INT NOT NULL,
    PRIMARY KEY (DEP_ID, FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE USUARIO_COMUM (
    USC_ORGAO_EMISSOR VARCHAR(10),
    USC_ID INT AUTO_INCREMENT PRIMARY KEY,
    USC_RG VARCHAR(15) NOT NULL,
    USC_CPF VARCHAR(20) NOT NULL,
    USC_DATA_NASCIMENTO DATE NOT NULL,
    USC_SENHA VARCHAR(200) NOT NULL,
    USC_SEXO INT NOT NULL,
    USC_NOME VARCHAR(180) NOT NULL,
    USC_ESTADO INT NOT NULL,
    USC_CIDADE VARCHAR(100) NOT NULL,
    USC_BAIRRO VARCHAR(100) NOT NULL,
    USC_NUMERO VARCHAR(10) NOT NULL,
    USC_LOGRADOURO VARCHAR(200) NOT NULL,
    UNIQUE (USC_CPF, USC_RG)
);

CREATE TABLE PACIENTES (
    PAC_ID INT AUTO_INCREMENT,
    PAC_EMAIL VARCHAR(200) NOT NULL,
    FK_USUARIO_COMUM_USC_ID INT NOT NULL,
    PRIMARY KEY (PAC_ID, FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE RESPONSAVEIS (
    RES_TEM_ALERGIA_MEDICA BOOLEAN NOT NULL,
    RES_QTD_FILHOS INT NOT NULL,
    RES_QUAIS_ALERGIAS VARCHAR(200),
    RES_TEL_CELULAR1 VARCHAR(20),
    RES_TEL_CELULAR2 VARCHAR(20),
    RES_QUAL_MEDICACAO VARCHAR(200),
    RES_QUAIS_TRAT_MED VARCHAR(200),
    RES_TEM_FILHOS BOOLEAN NOT NULL,
    RES_UTILIZA_MEDICACAO BOOLEAN NOT NULL,
    FK_PACIENTES_PAC_ID INT NOT NULL,
    FK_PACIENTES_FK_USUARIO_COMUM_USC_ID INT NOT NULL,
    PRIMARY KEY (FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE CONTABILIDADE (
    CON_ID INT AUTO_INCREMENT,
    FK_FUNCIONARIOS_FUN_ID INT NOT NULL,
    FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INT NOT NULL,
    PRIMARY KEY (CON_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE ADMINISTRATIVO (
    ADM_ID INT AUTO_INCREMENT,
    ADM_FUNCAO INT,
    ADM_DATA_ADMISSAO DATE NOT NULL,
    ADM_DATA_DEMISSAO DATE,
    ADM_CLINICA INT NOT NULL,
    ADM_SALARIO FLOAT NOT NULL,
    ADM_CRM VARCHAR(20) NOT NULL,
    ADM_TELEFONE_CELULAR VARCHAR(20) NOT NULL,
    FK_FUNCIONARIOS_FUN_ID INT NOT NULL,
    FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INT NOT NULL,
    PRIMARY KEY (ADM_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE CLINICAS_MEDICAS (
    CLI_ID INT AUTO_INCREMENT,
    CLI_RAZAO_SOCIAL VARCHAR(200) NOT NULL,
    CLI_DATA_FUNDACAO DATE NOT NULL,
    CLI_CNPJ VARCHAR(30) NOT NULL,
    CLI_CONTATO1 VARCHAR(20),
    CLI_CONTATO2 VARCHAR(20),
    FK_ADMINISTRATIVO_ADM_ID INT,
    FK_ADMINISTRATIVO_FK_FUNCIONARIOS_FUN_ID INT,
    FK_ADMINISTRATIVO_FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID INT,
    PRIMARY KEY (CLI_ID, FK_ADMINISTRATIVO_ADM_ID, FK_ADMINISTRATIVO_FK_FUNCIONARIOS_FUN_ID, FK_ADMINISTRATIVO_FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE CONTATOS_SETORIAIS (
    CSE_ID INT AUTO_INCREMENT PRIMARY KEY,
    CSE_SETOR VARCHAR(200) NOT NULL UNIQUE,
    CSE_TELEFONE_FIXO VARCHAR(20),
    CSE_EMAIL VARCHAR(200) NOT NULL,
    CSE_TELEFONE_CELULAR VARCHAR(20) NOT NULL
);

CREATE TABLE RESP_DEP (
    FK_RESPONSAVEIS_FK_PACIENTES_PAC_ID INT NOT NULL,
    FK_RESPONSAVEIS_FK_PACIENTES_FK_USUARIO_COMUM_USC_ID INT NOT NULL,
    FK_DEPENDENTES_DEP_ID INT,
    FK_DEPENDENTES_FK_PACIENTES_PAC_ID INT,
    FK_DEPENDENTES_FK_PACIENTES_FK_USUARIO_COMUM_USC_ID INT
);
 
ALTER TABLE ENFERMEIROS ADD CONSTRAINT FK_ENFERMEIROS_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES FUNCIONARIOS (FUN_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE MEDICOS ADD CONSTRAINT FK_MEDICOS_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES FUNCIONARIOS (FUN_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE FUNCIONARIOS ADD CONSTRAINT FK_FUNCIONARIOS_2
    FOREIGN KEY (FK_USUARIO_COMUM_USC_ID)
    REFERENCES USUARIO_COMUM (USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DEPENDENTES ADD CONSTRAINT FK_DEPENDENTES_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    REFERENCES PACIENTES (PAC_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTES_2
    FOREIGN KEY (FK_USUARIO_COMUM_USC_ID)
    REFERENCES USUARIO_COMUM (USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RESPONSAVEIS ADD CONSTRAINT FK_RESPONSAVEIS_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    REFERENCES PACIENTES (PAC_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONTABILIDADE ADD CONSTRAINT FK_CONTABILIDADE_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES FUNCIONARIOS (FUN_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ADMINISTRATIVO ADD CONSTRAINT FK_ADMINISTRATIVO_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES FUNCIONARIOS (FUN_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CLINICAS_MEDICAS ADD CONSTRAINT FK_CLINICAS_MEDICAS_2
    FOREIGN KEY (FK_ADMINISTRATIVO_ADM_ID, FK_ADMINISTRATIVO_FK_FUNCIONARIOS_FUN_ID, FK_ADMINISTRATIVO_FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    REFERENCES ADMINISTRATIVO (ADM_ID, FK_FUNCIONARIOS_FUN_ID, FK_FUNCIONARIOS_FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RESP_DEP ADD CONSTRAINT FK_RESP_DEP_1
    FOREIGN KEY (FK_RESPONSAVEIS_FK_PACIENTES_PAC_ID, FK_RESPONSAVEIS_FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    REFERENCES RESPONSAVEIS (FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE RESP_DEP ADD CONSTRAINT FK_RESP_DEP_2
    FOREIGN KEY (FK_DEPENDENTES_DEP_ID, FK_DEPENDENTES_FK_PACIENTES_PAC_ID, FK_DEPENDENTES_FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    REFERENCES DEPENDENTES (DEP_ID, FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIO_COMUM_USC_ID)
    ON DELETE SET NULL;