/* Modelo_MER1: */

CREATE TABLE FUNCIONARIO (
    FUN_ID Int,
    FUN_FUNCAO Int,
    FUN_CRM Varchar(20),
    FUN_SALARIO Float,
    FUN_CRM Varchar(20),
    FUN_PRONTUARIO Varchar(8),
    FUN_ADMISSAO Date,
    FUN_DEMISSAO Date,
    FUN_CLINICA Int,
    FUN_HOSPITAL Int,
    FK_USUARIO_COMUM_USC_ID Int,
    PRIMARY KEY (FUN_ID, FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE DEPENDENTE (
    DEP_ID Int,
    DEP_NV_PARENTESCO Int,
    FK_PACIENTE_PAC_ID Varchar(20),
    FK_PACIENTE_FK_USUARIO_COMUM_USC_ID Int,
    PRIMARY KEY (DEP_ID, FK_PACIENTE_PAC_ID, FK_PACIENTE_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE USUARIO_COMUM (
    USC_ID Int PRIMARY KEY,
    USC_NOME Varchar(180),
    USC_DATA_NASCIMENTO Date,
    USC_SEXO Int,
    USC_CPF Varchar(20),
    USC_RG Varchar(15),
    USC_ORGAO_EMISSOR Varchar(10),
    USC_SENHA Varchar(25)
);

CREATE TABLE PACIENTE (
    PAC_ID Varchar(20),
    PAC_EMAIL Varchar(200),
    FK_USUARIO_COMUM_USC_ID Int,
    PRIMARY KEY (PAC_ID, FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE RESPONSAVEL (
    USU_ID Int,
    USU_TEL_CELULAR1 Varchar(20),
    USU_TEL_CELULAR2 Varchar(20),
    USU_TEM_FILHOS Boolean,
    USU_QTD_FILHOS Int,
    USU_UTILIZA_MEDICACAO Boolean,
    USU_QUAIS_MEDICACOES Varchar(200),
    USU_TEM_ALERGIA_MEDICA Boolean,
    USU_QUAIS_ALERGIAS Varchar(200),
    USU_TRAT_MEDICO Boolean,
    USU_QUAIS_TRAT_MED Varchar(200),
    USU_DOENCAS_CRONICAS Boolean,
    USU_QUAIS_DOENCAS_CRON Varchar(200),
    FK_PACIENTE_PAC_ID Varchar(20),
    FK_PACIENTE_FK_USUARIO_COMUM_USC_ID Int,
    PRIMARY KEY (USU_ID, FK_PACIENTE_PAC_ID, FK_PACIENTE_FK_USUARIO_COMUM_USC_ID)
);

CREATE TABLE RESP_DEP (
    FK_RESPONSAVEL_USU_ID Int,
    FK_RESPONSAVEL_FK_PACIENTE_PAC_ID Varchar(20),
    FK_RESPONSAVEL_FK_PACIENTE_FK_USUARIO_COMUM_USC_ID Int,
    FK_DEPENDENTE_DEP_ID Int,
    FK_DEPENDENTE_FK_PACIENTE_PAC_ID Varchar(20),
    FK_DEPENDENTE_FK_PACIENTE_FK_USUARIO_COMUM_USC_ID Int
);
 
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_2
    FOREIGN KEY (FK_USUARIO_COMUM_USC_ID)
    REFERENCES USUARIO_COMUM (USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_DEPENDENTE_2
    FOREIGN KEY (FK_PACIENTE_PAC_ID, FK_PACIENTE_FK_USUARIO_COMUM_USC_ID)
    REFERENCES PACIENTE (PAC_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PACIENTE ADD CONSTRAINT FK_PACIENTE_2
    FOREIGN KEY (FK_USUARIO_COMUM_USC_ID)
    REFERENCES USUARIO_COMUM (USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RESPONSAVEL ADD CONSTRAINT FK_RESPONSAVEL_2
    FOREIGN KEY (FK_PACIENTE_PAC_ID, FK_PACIENTE_FK_USUARIO_COMUM_USC_ID)
    REFERENCES PACIENTE (PAC_ID, FK_USUARIO_COMUM_USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RESP_DEP ADD CONSTRAINT FK_RESP_DEP_1
    FOREIGN KEY (FK_RESPONSAVEL_USU_ID, FK_RESPONSAVEL_FK_PACIENTE_PAC_ID, FK_RESPONSAVEL_FK_PACIENTE_FK_USUARIO_COMUM_USC_ID)
    REFERENCES RESPONSAVEL (USU_ID, FK_PACIENTE_PAC_ID, FK_PACIENTE_FK_USUARIO_COMUM_USC_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE RESP_DEP ADD CONSTRAINT FK_RESP_DEP_2
    FOREIGN KEY (FK_DEPENDENTE_DEP_ID, FK_DEPENDENTE_FK_PACIENTE_PAC_ID, FK_DEPENDENTE_FK_PACIENTE_FK_USUARIO_COMUM_USC_ID)
    REFERENCES DEPENDENTE (DEP_ID, FK_PACIENTE_PAC_ID, FK_PACIENTE_FK_USUARIO_COMUM_USC_ID)
    ON DELETE SET NULL;