/* Modelo_Logico2: */

CREATE TABLE FUNCIONARIOS (
    FUN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_USUARIO_COMUM_USC_ID INTEGER,
    FUN_PRONTUARIO VARCHAR(8) NOT NULL,
    CATEGORIA INTEGER NOT NULL /*CATEGORIAS
1 - Médico
2 - ENFERMEIRO
3 - CONTABIL
4 - SECRETARIADO
5 - ADMINISTRATIVO
6 - HOSP/CLINICA MÉDICA */
);

CREATE TABLE ENFERMEIROS (
    ENF_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_FUNCIONARIOS_FUN_ID INTEGER
);

CREATE TABLE MEDICOS (
    MED_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_FUNCIONARIOS_FUN_ID INTEGER
);

CREATE TABLE DEPENDENTES (
    DEP_NV_PARENTESCO INTEGER NOT NULL,
    DEP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_PACIENTES_PAC_ID INTEGER,
    FK_RESPONSAVEIS_RES_ID INTEGER
);

CREATE TABLE USUARIO_COMUM (
    USC_ORGAO_EMISSOR VARCHAR(10),
    USC_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USC_RG VARCHAR(15) NOT NULL,
    USC_CPF VARCHAR(20) NOT NULL,
    USC_DATA_NASCIMENTO DATE NOT NULL,
    USC_SENHA VARCHAR(200) NOT NULL,
    USC_SEXO INTEGER NOT NULL,
    USC_NOME VARCHAR(180) NOT NULL,
    USC_ESTADO INTEGER NOT NULL,
    USC_CIDADE VARCHAR(100) NOT NULL,
    USC_BAIRRO VARCHAR(100) NOT NULL,
    USC_NUMERO VARCHAR(10) NOT NULL,
    USC_LOGRADOURO VARCHAR(200) NOT NULL,
    UNIQUE (USC_RG, USC_CPF)
);

CREATE TABLE PACIENTES (
    PAC_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PAC_EMAIL VARCHAR(200) NOT NULL,
    FK_USUARIO_COMUM_USC_ID INTEGER
);

CREATE TABLE RESPONSAVEIS (
    RES_TEM_ALERGIA_MEDICA BOOLEAN NOT NULL,
    RES_QTD_FILHOS INTEGER NOT NULL,
    RES_QUAIS_ALERGIAS VARCHAR(200),
    RES_TEL_CELULAR1 VARCHAR(20),
    RES_TEL_CELULAR2 VARCHAR(20),
    RES_QUAL_MEDICACAO VARCHAR(200),
    RES_QUAIS_TRAT_MED VARCHAR(200),
    RES_TEM_FILHOS BOOLEAN NOT NULL,
    RES_UTILIZA_MEDICACAO BOOLEAN NOT NULL,
    RES_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_PACIENTES_PAC_ID INTEGER
);

CREATE TABLE CONTABILIDADE (
    CON_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_FUNCIONARIOS_FUN_ID INTEGER
);

CREATE TABLE ADMINISTRATIVO (
    ADM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ADM_FUNCAO INTEGER NOT NULL,
    ADM_DATA_ADMISSAO DATE NOT NULL,
    ADM_DATA_DEMISSAO DATE,
    ADM_CLINICA INTEGER NOT NULL,
    ADM_SALARIO FLOAT NOT NULL,
    ADM_CRM VARCHAR(20) NOT NULL,
    ADM_TELEFONE_CELULAR VARCHAR(20) NOT NULL,
    FK_FUNCIONARIOS_FUN_ID INTEGER
);

/*NÃO HOUVE NECESSIDADE DESSA TABELA DURANTE A INTEGRÇÃO - IGNORADA
/*CREATE TABLE CLINICAS_MEDICAS (
    CLI_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CLI_RAZAO_SOCIAL VARCHAR(200) NOT NULL,
    CLI_DATA_FUNDACAO DATE NOT NULL,
    CLI_CNPJ VARCHAR(30) NOT NULL,
    CLI_CONTATO1 VARCHAR(20),
    CLI_CONTATO2 VARCHAR(20),
    FK_ADMINISTRATIVO_ADM_ID INTEGER
);*/

CREATE TABLE CONTATOS_SETORIAIS (
    CSE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CSE_SETOR VARCHAR(200) UNIQUE,
    CSE_TELEFONE_FIXO VARCHAR(20),
    CSE_EMAIL VARCHAR(200) NOT NULL,
    CSE_TELEFONE_CELULAR VARCHAR(20) NOT NULL
);
 
ALTER TABLE ENFERMEIROS ADD CONSTRAINT FK_ENFERMEIROS_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID)
    REFERENCES FUNCIONARIOS (FUN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE MEDICOS ADD CONSTRAINT FK_MEDICOS_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID)
    REFERENCES FUNCIONARIOS (FUN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE FUNCIONARIOS ADD CONSTRAINT FK_FUNCIONARIOS_2
    FOREIGN KEY (FK_USUARIO_COMUM_USC_ID)
    REFERENCES USUARIO_COMUM (USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DEPENDENTES ADD CONSTRAINT FK_DEPENDENTES_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DEPENDENTES ADD CONSTRAINT FK_DEPENDENTES_3
    FOREIGN KEY (FK_RESPONSAVEIS_RES_ID)
    REFERENCES RESPONSAVEIS (RES_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTES_2
    FOREIGN KEY (FK_USUARIO_COMUM_USC_ID)
    REFERENCES USUARIO_COMUM (USC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RESPONSAVEIS ADD CONSTRAINT FK_RESPONSAVEIS_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONTABILIDADE ADD CONSTRAINT FK_CONTABILIDADE_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID)
    REFERENCES FUNCIONARIOS (FUN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ADMINISTRATIVO ADD CONSTRAINT FK_ADMINISTRATIVO_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID)
    REFERENCES FUNCIONARIOS (FUN_ID)
    ON DELETE CASCADE;
 
/*ALTER TABLE CLINICAS_MEDICAS ADD CONSTRAINT FK_CLINICAS_MEDICAS_2
    FOREIGN KEY (FK_ADMINISTRATIVO_ADM_ID)
    REFERENCES ADMINISTRATIVO (ADM_ID)
    ON DELETE CASCADE;*/